"""add source status column

Revision ID: d6a2ae340f36
Revises: f64f5b80586f
Create Date: 2026-03-05 14:24:14.863205

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6a2ae340f36'
down_revision: Union[str, Sequence[str], None] = 'f64f5b80586f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('source', sa.Column('status', sa.String(), nullable=False, server_default='pending'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('source', 'status')
    # ### end Alembic commands ###
